#!/bin/bash
set -xeuo pipefail
basedir=$(cd $(dirname $0) && pwd)
origdir=$(pwd)
build=atomic-ws
cachedir=/var/cache/treecompose/${build}
buildscriptsdir=$(cd atomic-ws && pwd)
ref=atomicws/fedora/x86_64/continuous
tempdir=$(mktemp -t -d "stamp.XXXXXX")
touch ${tempdir}/.testtmp
function cleanup () {
    if test -n "${TEST_SKIP_CLEANUP:-}"; then
	echo "Skipping cleanup of ${tempdir}"
    else if test -f ${tempdir}/.testtmp; then
	rm "${tempdir}" -rf
    fi
    fi
}
trap cleanup EXIT

. ~/rsync-password.sh 
# Ensure we're operating on a clean base
(cd ${buildscriptsdir} && git clean -dfx && git reset --hard HEAD)

mkdir -p build
cd build

mkdir -p ${build}/ostree
# Ensure the data is populated initially
if ! test -d ${build}/ostree/repo; then
    ostree --repo=${build}/ostree/repo init --mode=archive
fi
rsync --stats -a ${build}/ sig-atomic@artifacts.ci.centos.org::sig-atomic/${build}/
sudo mkdir -p ${cachedir}
sudo chown -R -h $USER:$USER ${cachedir}
mkdir -p ${cachedir}/ostree
rsync --delete --stats -Hrlpt sig-atomic@artifacts.ci.centos.org::sig-atomic/${build}/ostree/ ${cachedir}/ostree/
repo=${cachedir}/ostree/repo

cachebuildrepo=${cachedir}/build-repo
if ! test -d ${cachebuildrepo}/objects; then
    ostree --repo=${cachebuildrepo} init --mode=bare-user
fi
parent=$(ostree --repo=${repo} rev-parse ${ref} 2>/dev/null || true)
if test -n "${parent}"; then
    ostree --repo=${cachebuildrepo} pull-local ${repo} ${ref}
fi
compose_args=""
if test -f ${buildscriptsdir}/centos-ci/override-treecompose-cache; then
    override=$(cat ${buildscriptsdir}/centos-ci/override-treecompose-cache)
    if test ${override} = ${parent}; then
	compose_args="--force-nocache"
    fi
fi

## Update release tags
#$basedir/do-release-tags --repo=ostree/repo --releases=${buildscriptsdir}/releases.yml

# Work around https://lists.centos.org/pipermail/ci-users/2016-July/000302.html
for f in ${buildscriptsdir}/*.repo; do
    sed -i -e 's,https://ci.centos.org/artifacts/,http://artifacts.ci.centos.org/,g' ${f}
done
(cd ${buildscriptsdir}/centos-ci/containers && sudo make)
sudo docker run --privileged -v ${cachedir}:/srv/cache -v ${buildscriptsdir}:/srv/src -v ${tempdir}:/srv/tmp -v $(pwd):/srv/compose \
     rpm-ostree compose tree ${compose_args} --touch-if-changed=/srv/tmp/treecompose.stamp --repo=/srv/cache/build-repo /srv/src/atomicws-continuous-25.json
if test -f ${tempdir}/treecompose.stamp; then
    sudo chown -R -h $USER:$USER ${cachebuildrepo}
    ostree --repo=${repo} pull-local ${cachebuildrepo} ${ref}
    ostree --repo=${repo} summary -u
    if test -n "${parent}"; then
	rpm-ostree db --repo=${repo} diff ${ref}{^,}
	ostree --repo=${repo} static-delta generate ${ref}
    fi
    ostree --repo=${repo} prune --keep-younger-than='30 days ago' --refs-only
fi

# Always regenerate this right now since otherwise we have to track
# potential changes from anything above.
ostree --repo=${repo} summary -u

rsync --delete --stats -a ${cachedir}/ostree/ sig-atomic@artifacts.ci.centos.org::sig-atomic/${build}/ostree/
