#!/bin/bash
set -xeuo pipefail

basedir=$(cd $(dirname $0) && pwd)

. ~/rsync-password.sh 

mkdir -p build
cd build
build=atomic-ws

mkdir -p ${build}/rdgo
# Ensure the data is populated initially
rsync --stats -a ${build}/ sig-atomic@artifacts.ci.centos.org::sig-atomic/${build}/
origdir=$(pwd)
cd ${build}
for v in rdgo; do
    rsync --delete --stats -a sig-atomic@artifacts.ci.centos.org::sig-atomic/${build}/${v}/ ${v}/
done

build_success=false
if ${basedir}/run-rdgo ${origdir}; then
    build_success=true
fi

for v in rdgo; do
    rsync --delete --stats -a ${v}/ sig-atomic@artifacts.ci.centos.org::sig-atomic/${build}/${v}/
done
if test "${build_success}" = false; then
    echo "Build failed, see logs above"; exit 1
fi
