#!/bin/bash
set -xeuo pipefail
basedir=$(cd $(dirname $0) && pwd)
. ${basedir}/libtask.sh
. ${basedir}/libtoolbox.sh

cachedir=/var/cache/treecompose/${build}

mkdir -p ${build}/ostree
# Ensure the data is populated initially
if ! test -d ${build}/ostree/repo; then
    ostree --repo=${build}/ostree/repo init --mode=archive
fi
rsync --stats -a ${build}/ sig-atomic@artifacts.ci.centos.org::sig-atomic/${build}/

sudo mkdir -p ${cachedir}
sudo chown -R -h $USER:$USER ${cachedir}
mkdir -p ${cachedir}/ostree
rsync --delete --stats -Hrlpt sig-atomic@artifacts.ci.centos.org::sig-atomic/${build}/ostree/ ${cachedir}/ostree/
repo=${cachedir}/ostree/repo

# Regenerate to ensure this up to date
ostree --repo=${repo} summary -u
echo "----"
ostree --repo=${repo} log ${ref} | head -100
echo "----"


cachebuildrepo=$(pwd)/build-repo
if ! test -d ${cachebuildrepo}/objects; then
    ostree --repo=${cachebuildrepo} init --mode=bare-user
fi
parent=$(ostree --repo=${repo} rev-parse ${ref} 2>/dev/null || true)
if test -n "${parent}"; then
    ostree --repo=${cachebuildrepo} pull-local ${repo} ${ref}
fi
compose_args=""
if test -f ${buildscriptsdir}/centos-ci/override-treecompose-cache; then
    override=$(cat ${buildscriptsdir}/centos-ci/override-treecompose-cache)
    if test ${override} = ${parent}; then
	compose_args="--force-nocache"
    fi
fi

## Update release tags
$basedir/do-release-tags --repo=${repo} --releases=${buildscriptsdir}/releases.yml

# Work around https://lists.centos.org/pipermail/ci-users/2016-July/000302.html
for f in ${buildscriptsdir}/*.repo; do
    sed -i -e 's,https://ci.centos.org/artifacts/,http://artifacts.ci.centos.org/,g' ${f}
done
(cd ${buildscriptsdir}/centos-ci/containers && sudo make)
sudo docker run --privileged -v ${cachedir}:/srv/cache -v ${buildscriptsdir}:/srv/src -v ${WORKSPACE}:/srv/tmp -v $(pwd):/srv/compose \
     rpm-ostree compose tree ${compose_args} --touch-if-changed=/srv/tmp/treecompose.stamp --repo=/srv/cache/build-repo /srv/src/atomicws-continuous-25.json
touch ${WORKSPACE}/treecompose.stamp
if test -f ${WORKSPACE}/treecompose.stamp; then
    sudo chown -R -h $USER:$USER ${cachebuildrepo}
    ostree --repo=${repo} pull-local ${cachebuildrepo} ${ref}
    ostree --repo=${repo} summary -u
    if test -n "${parent}"; then
	rpm-ostree db --repo=${repo} diff ${ref}{^,}
	ostree --repo=${repo} static-delta generate ${ref}
    fi
    ostree --repo=${repo} prune --keep-younger-than='30 days ago' --refs-only
fi

# Always regenerate this right now since otherwise we have to track
# potential changes from anything above.
ostree --repo=${repo} summary -u

rsync --delete --stats -a ${cachedir}/ostree/ sig-atomic@artifacts.ci.centos.org::sig-atomic/${build}/ostree/
