#!/bin/bash
set -xeuo pipefail
basedir=$(cd $(dirname $0) && pwd)
build=fedora-workstation
buildscriptsdir=$(cd workstation-ostree-config && pwd)
ref=fedora/24/x86_64/desktop/continuous

. ${basedir}/libtoolbox.sh
. ~/rsync-password.sh 

prepare_image_build installer
sudo rpm-ostree-toolbox installer ${toolbox_base_args} -o ${version} --overwrite
finish_image_build installer
